name: Unit Tests on halo-third-party-sdk

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Building halo-third-party-sdk-model
      working-directory: halo-third-party-sdk-model
      run: npm install && npm run release && npm link
    - name: Building halo-third-party-sdk-events
      working-directory: halo-third-party-sdk-events
      run: npm link @amzn/halo-third-party-sdk-model && npm install && npm run test && npm run release
